version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        - PORT=$PORT
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/folha-ponto
    env_file:
      - .env
    ports:
      - $PORT:$PORT
    volumes:
      - .:/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=folha-ponto
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 
